"""Review Formatter — stitches sections into a complete Markdown review + biblio."""
from __future__ import annotations

from datetime import date
from typing import Any

from src.export.bibtex import source_to_bibtex


def format_review(
    title: str,
    sections: list[tuple[str, str]],  # (heading, body)
    citation_pool: dict[str, dict[str, Any]],  # tag -> source dict
) -> str:
    """Stitch ordered sections into a complete Markdown review document."""
    lines: list[str] = [
        f"# {title}",
        "",
        f"_Generated by ResearGent — {date.today().isoformat()}_",
        "",
        "---",
        "",
    ]

    for heading, body in sections:
        lines.append(f"## {heading}")
        lines.append("")
        lines.append(body)
        lines.append("")

    # Bibliography
    if citation_pool:
        lines.append("---")
        lines.append("")
        lines.append("## References")
        lines.append("")
        for tag in sorted(citation_pool.keys(), key=lambda t: int(t[1:])):
            src = citation_pool[tag]
            bib = source_to_bibtex(src, tag)
            lines.append("```bibtex")
            lines.append(bib)
            lines.append("```")
            lines.append("")

    return "\n".join(lines).strip() + "\n"