"""
PDF exporter for literature reviews.
Uses ReportLab to build a beautifully formatted academic-style PDF.
"""

from __future__ import annotations

import re
import unicodedata
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    HRFlowable,
    Preformatted,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch


def markdown_to_pdf_bytes(title: str, markdown: str) -> bytes:
    """
    Parse the literature review markdown and compile it into a styled PDF.
    Returns the PDF as raw bytes.
    """
    buffer = BytesIO()
    
    # Page setup - Standard academic 1-inch margins
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )
    
    styles = getSampleStyleSheet()
    
    # Custom academic styles (using serif Times-Roman for a classic scholarly feel)
    title_style = ParagraphStyle(
        "AcademicTitle",
        parent=styles["Normal"],
        fontName="Times-Bold",
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0f172a"),  # Deep slate
        alignment=1,  # Centered
        spaceAfter=15,
    )
    
    meta_style = ParagraphStyle(
        "AcademicMeta",
        parent=styles["Normal"],
        fontName="Times-Italic",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#64748b"),  # Cool grey
        alignment=1,  # Centered
        spaceAfter=20,
    )
    
    h1_style = ParagraphStyle(
        "AcademicH1",
        parent=styles["Normal"],
        fontName="Times-Bold",
        fontSize=16,
        leading=20,
        textColor=colors.HexColor("#1e293b"),
        spaceBefore=18,
        spaceAfter=10,
        keepWithNext=True,
    )
    
    h2_style = ParagraphStyle(
        "AcademicH2",
        parent=styles["Normal"],
        fontName="Times-Bold",
        fontSize=13,
        leading=17,
        textColor=colors.HexColor("#334155"),
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True,
    )
    
    body_style = ParagraphStyle(
        "AcademicBody",
        parent=styles["Normal"],
        fontName="Times-Roman",
        fontSize=10.5,
        leading=15,
        wordWrap="CJK",
        textColor=colors.HexColor("#1e293b"),
        spaceAfter=10,
        firstLineIndent=0.25 * inch,  # Classic academic paragraph indent
    )
    
    # Overrides firstLineIndent for the first paragraph of a section
    body_first_style = ParagraphStyle(
        "AcademicBodyFirst",
        parent=body_style,
        firstLineIndent=0,
    )
    
    code_style = ParagraphStyle(
        "BibTeXCode",
        parent=styles["Normal"],
        fontName="Courier",
        fontSize=8.5,
        leading=11,
        textColor=colors.HexColor("#0f172a"),
        backColor=colors.HexColor("#f8fafc"),
        borderColor=colors.HexColor("#e2e8f0"),
        borderWidth=0.5,
        borderPadding=6,
        spaceAfter=12,
    )

    story = []
    
    in_code_block = False
    code_lines = []
    text_lines = []
    is_first_para_of_section = True
    
    def add_code_block() -> None:
        if code_lines:
            # Courier is fixed width: 82 characters fit inside the printable
            # page width, and Preformatted inserts continuation lines for
            # long BibTeX URLs and other unbroken text.
            story.append(Preformatted(
                _normalize_pdf_text("\n".join(code_lines)),
                code_style,
                maxLineLength=82,
                newLineChars="  ",
            ))
            code_lines.clear()

    def add_text_block() -> None:
        nonlocal is_first_para_of_section
        block = "\n".join(text_lines).strip()
        text_lines.clear()
        if not block:
            return
            
        # Heading 1 (e.g. # Document Title)
        if block.startswith("# "):
            title_text = block[2:].strip()
            story.append(Paragraph(_clean_inline_markdown(title_text), title_style))
            is_first_para_of_section = True
            return
            
        # Heading 2 (e.g. ## Section Name)
        if block.startswith("## "):
            sec_text = block[3:].strip()
            story.append(Paragraph(_clean_inline_markdown(sec_text), h1_style))
            is_first_para_of_section = True
            return
            
        # Heading 3 (e.g. ### Subsection Name)
        if block.startswith("### "):
            sub_text = block[4:].strip()
            story.append(Paragraph(_clean_inline_markdown(sub_text), h2_style))
            is_first_para_of_section = True
            return
            
        # Metadata / italic lines (e.g. _Generated by..._)
        if block.startswith("_") and block.endswith("_"):
            meta_text = block[1:-1].strip()
            story.append(Paragraph(_clean_inline_markdown(meta_text), meta_style))
            return
            
        # Horizontal Rule (e.g. ---)
        if block == "---":
            story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cbd5e1"), spaceAfter=15, spaceBefore=10))
            is_first_para_of_section = True
            return
            
        # Standard paragraph
        cleaned_text = _clean_inline_markdown(" ".join(line.strip() for line in block.splitlines()))
        current_style = body_first_style if is_first_para_of_section else body_style
        story.append(Paragraph(cleaned_text, current_style))
        is_first_para_of_section = False

    # Parse fences line by line so a code fence next to other text or BibTeX
    # with blank lines cannot leak raw backticks into the final document.
    for line in markdown.splitlines():
        if line.strip().startswith("```"):
            if in_code_block:
                add_code_block()
                in_code_block = False
            else:
                add_text_block()
                in_code_block = True
            continue
        if in_code_block:
            code_lines.append(line)
        elif line.strip():
            text_lines.append(line)
        else:
            add_text_block()

    if in_code_block:
        add_code_block()
    else:
        add_text_block()

    # Build the document
    # Simple footer page numbering
    def add_page_number(canvas, doc):
        canvas.saveState()
        canvas.setFont("Times-Roman", 9)
        canvas.setFillColor(colors.HexColor("#64748b"))
        page_num = canvas.getPageNumber()
        canvas.drawRightString(
            letter[0] - 0.75 * inch,
            0.4 * inch,
            f"Page {page_num}"
        )
        canvas.drawString(
            0.75 * inch,
            0.4 * inch,
            "ResearGent Literature Review"
        )
        canvas.restoreState()

    doc.build(story, onFirstPage=add_page_number, onLaterPages=add_page_number)
    pdf_data = buffer.getvalue()
    buffer.close()
    return pdf_data


def _clean_inline_markdown(text: str) -> str:
    """
    Safely escapes XML-sensitive characters while converting markdown-style bold,
    italic, links, and code snippets into ReportLab's XML tags.
    """
    text = _normalize_pdf_text(text)

    # Normalize punctuation to glyphs supported by ReportLab's built-in fonts.
    text = text.replace("\u2011", "-")  # Non-breaking hyphen
    text = text.replace("\u2010", "-")  # Hyphen
    text = text.replace("\u2012", "-")  # Figure dash
    text = text.replace("\u2013", "-")  # En-dash
    text = text.replace("\u2014", " -- ")  # Em-dash
    text = text.replace("\u2015", "-")  # Horizontal bar
    text = text.replace("\u2018", "'").replace("\u2019", "'")  # Smart single quotes
    text = text.replace("\u201c", '"').replace("\u201d", '"')  # Smart double quotes

    # 1. Escape basic XML entities first
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    
    # 2. Convert Bold (**text** or __text__)
    text = re.sub(r'\*\*(.*?)\*\*|__(.*?)__', r'<b>\1\2</b>', text)
    
    # 3. Convert Italic (*text* or _text_)
    # Guarding against underscores in URLs or other contexts
    text = re.sub(r'\*(.*?)\*|_(.*?)_', r'<i>\1\2</i>', text)
    
    # 4. Highlight citations like [S1], [S2]
    text = re.sub(r'\[(S\d+)\]', r'<b>[\1]</b>', text)
    
    # 5. Convert inline backticks (`code`)
    text = re.sub(r'`(.*?)`', r'<font name="Courier" color="#0f172a"><b>\1</b></font>', text)
    
    # 6. Convert markdown links [text](url) to ReportLab links
    # ReportLab supports <a href="url">text</a>
    text = re.sub(
        r'\[(.*?)\]\((.*?)\)',
        r'<a href="\2"><font color="#0284c7"><u>\1</u></font></a>',
        text
    )
    
    return text


def _normalize_pdf_text(text: str) -> str:
    """Convert mathematical Unicode glyphs to readable, copyable PDF text."""
    subscripts = str.maketrans({
        "₀": "_0", "₁": "_1", "₂": "_2", "₃": "_3", "₄": "_4",
        "₅": "_5", "₆": "_6", "₇": "_7", "₈": "_8", "₉": "_9",
        "₊": "_+", "₋": "_-", "₌": "_=", "₍": "_(", "₎": ")",
        "⁰": "^0", "¹": "^1", "²": "^2", "³": "^3", "⁴": "^4",
        "⁵": "^5", "⁶": "^6", "⁷": "^7", "⁸": "^8", "⁹": "^9",
        "⁺": "^+", "⁻": "^-", "⁼": "^=", "⁽": "^(", "⁾": ")",
        "ₐ": "_a", "ₑ": "_e", "ₕ": "_h", "ᵢ": "_i", "ⱼ": "_j",
        "ₖ": "_k", "ₗ": "_l", "ₘ": "_m", "ₙ": "_n", "ₒ": "_o",
        "ₚ": "_p", "ᵣ": "_r", "ₛ": "_s", "ₜ": "_t", "ᵤ": "_u",
        "ᵥ": "_v", "ₓ": "_x", "ᵦ": "_beta", "ᵧ": "_gamma",
        "ᵨ": "_rho", "ᵩ": "_phi", "ᵪ": "_chi",
        "ᵃ": "^a", "ᵇ": "^b", "ᶜ": "^c", "ᵈ": "^d", "ᵉ": "^e",
        "ᶠ": "^f", "ᵍ": "^g", "ʰ": "^h", "ⁱ": "^i", "ʲ": "^j",
        "ᵏ": "^k", "ˡ": "^l", "ᵐ": "^m", "ⁿ": "^n", "ᵒ": "^o",
        "ᵖ": "^p", "ʳ": "^r", "ˢ": "^s", "ᵗ": "^t", "ᵘ": "^u",
        "ᵛ": "^v", "ʷ": "^w", "ˣ": "^x", "ʸ": "^y", "ᶻ": "^z",
        "ᴬ": "^A", "ᴮ": "^B", "ᴰ": "^D", "ᴱ": "^E", "ᴳ": "^G",
        "ᴴ": "^H", "ᴵ": "^I", "ᴶ": "^J", "ᴷ": "^K", "ᴸ": "^L",
        "ᴹ": "^M", "ᴺ": "^N", "ᴼ": "^O", "ᴾ": "^P", "ᴿ": "^R",
        "ᵀ": "^T", "ᵁ": "^U", "ⱽ": "^V", "ᵂ": "^W",
    })
    symbols = {
        "∝": " proportional to ", "≤": " <= ", "≥": " >= ",
        "≠": " != ", "≈": " approximately ", "×": " x ",
        "·": " * ", "∑": "sum", "∏": "product", "∫": "integral",
        "√": "sqrt", "∞": "infinity", "∈": " in ", "∉": " not in ",
        "→": " -> ", "←": " <- ", "↔": " <-> ", "∂": "d",
        "∇": "nabla", "−": "-", "□": "[missing symbol]", "�": "[unknown symbol]",
    }
    normalized = unicodedata.normalize("NFKD", text.translate(subscripts))
    output: list[str] = []
    for char in normalized:
        if unicodedata.combining(char):
            continue
        if char in symbols:
            output.append(symbols[char])
            continue
        if "GREEK" in unicodedata.name(char, ""):
            name = unicodedata.name(char).split(" LETTER ")[-1]
            name = re.sub(r"^(SMALL|CAPITAL) ", "", name).lower().replace("lamda", "lambda")
            output.append(name)
            continue
        if char in "\u2010\u2011\u2012\u2013\u2014\u2015":
            output.append("-" if char != "\u2014" else " -- ")
            continue
        if char in "\u2018\u2019":
            output.append("'")
            continue
        if char in "\u201c\u201d":
            output.append('"')
            continue
        try:
            char.encode("cp1252")
            output.append(char)
        except UnicodeEncodeError:
            output.append(f"[U+{ord(char):04X}]")
    return "".join(output)
